# Generated by Django 5.2.18 on 2026-10-06 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('window_start', models.DateTimeField()),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('timezone', models.CharField(default='Europe/Brussels', max_length=64)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('kind', models.CharField(choices=[('meeting', 'Meeting'), ('break', 'Break')], max_length=8)),
                ('title', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'start'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month')], max_length=5)),
                ('date', models.DateField()),
                ('text', models.TextField(blank=True, max_length=10000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='Europe/Brussels', max_length=64)),
                ('day_start', models.TimeField(default='09:00')),
                ('day_end', models.TimeField(default='17:00')),
                ('focus_minutes', models.PositiveSmallIntegerField(default=25)),
                ('short_break', models.PositiveSmallIntegerField(default=5)),
                ('long_break', models.PositiveSmallIntegerField(default=15)),
                ('long_every', models.PositiveSmallIntegerField(default=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('kind', models.CharField(choices=[('focus', 'Focus'), ('meeting', 'Meeting')], default='focus', max_length=8)),
                ('title', models.CharField(default='Open focus', max_length=200)),
                ('status', models.CharField(choices=[('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='running', max_length=10)),
                ('started_at', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('ended_at', models.DateTimeField(null=True)),
                ('remaining_seconds', models.PositiveIntegerField()),
                ('planned_seconds', models.PositiveIntegerField()),
                ('elapsed_seconds', models.PositiveIntegerField(default=0)),
                ('resumed_at', models.DateTimeField()),
                ('break_until', models.DateTimeField(null=True)),
                ('effort', models.PositiveSmallIntegerField(null=True)),
                ('reflection', models.TextField(blank=True, max_length=2000)),
                ('reviewed', models.BooleanField(default=False)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='focus.block')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['started_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('position', models.PositiveIntegerField(default=0)),
                ('done', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('percent', models.PositiveSmallIntegerField(default=100)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='focus.session')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='focus.task')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['user', 'date'], name='focus_block_user_id_9268dc_idx'),
        ),
        migrations.AddConstraint(
            model_name='block',
            constraint=models.CheckConstraint(condition=models.Q(('end__gt', models.F('start'))), name='block_positive_length'),
        ),
        migrations.AddConstraint(
            model_name='note',
            constraint=models.UniqueConstraint(fields=('user', 'period', 'date'), name='unique_period_note'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['user', 'date', 'status'], name='focus_sessi_user_id_635e51_idx'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['running', 'paused'])), fields=('user',), name='one_active_session'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), fields=('block',), name='one_session_per_block'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.CheckConstraint(condition=models.Q(('effort__isnull', True), ('effort__lte', 5), _connector='OR'), name='effort_zero_to_five'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'archived', 'position'], name='focus_task_user_id_958fff_idx'),
        ),
        migrations.AddConstraint(
            model_name='allocation',
            constraint=models.CheckConstraint(condition=models.Q(('percent__gte', 1), ('percent__lte', 100)), name='allocation_percent_range'),
        ),
    ]
