# Generated by Django 5.2.18 on 2026-10-06 22:42

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='day_end',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='day_start',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
