# Generated by Django 5.2.18 on 2026-10-07 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_effort(apps, schema_editor):
    Session = apps.get_model("focus", "Session")
    Allocation = apps.get_model("focus", "Allocation")
    for session in Session.objects.exclude(effort=None).iterator():
        rows = list(Allocation.objects.filter(session_id=session.id).order_by("id"))
        if not rows:
            continue
        total = sum(row.percent for row in rows) or 100
        raw = [session.effort * row.percent / total for row in rows]
        amounts = [int(value) for value in raw]
        for index in sorted(range(len(rows)), key=lambda i: raw[i] - amounts[i], reverse=True)[:session.effort - sum(amounts)]:
            amounts[index] += 1
        for row, amount in zip(rows, amounts):
            row.sand = amount
        Allocation.objects.bulk_update(rows, ["sand"])


def restore_percentages(apps, schema_editor):
    Allocation = apps.get_model("focus", "Allocation")
    Session = apps.get_model("focus", "Session")
    for session in Session.objects.all().iterator():
        rows = list(Allocation.objects.filter(session_id=session.id).order_by("id"))
        if not rows:
            continue
        weights = [row.sand or 1 for row in rows]
        amounts = [max(1, int(100 * weight / sum(weights))) for weight in weights]
        amounts[0] += 100 - sum(amounts)
        for row, amount in zip(rows, amounts):
            row.percent = amount
        Allocation.objects.bulk_update(rows, ["percent"])


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0002_alter_preferences_day_end_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('meeting', 'Meeting'), ('break', 'Break')], max_length=8)),
                ('timezone', models.CharField(max_length=64)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('weekday', models.PositiveSmallIntegerField()),
                ('interval_weeks', models.PositiveSmallIntegerField(default=1)),
                ('anchor_date', models.DateField()),
                ('effective_from', models.DateField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='allocation',
            name='allocation_percent_range',
        ),
        migrations.AddField(
            model_name='allocation',
            name='sand',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.RunPython(preserve_effort, restore_percentages),
        migrations.RemoveField(
            model_name='allocation',
            name='percent',
        ),
        migrations.AddField(
            model_name='block',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='block',
            name='fixed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='block',
            name='occurrence_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preferences',
            name='frozen_through',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preferences',
            name='next_focus_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='allocation',
            constraint=models.CheckConstraint(condition=models.Q(('sand__lte', 5)), name='allocation_sand_range'),
        ),
        migrations.AddField(
            model_name='blocktemplate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='block',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='focus.blocktemplate'),
        ),
        migrations.AddConstraint(
            model_name='block',
            constraint=models.UniqueConstraint(fields=('template', 'occurrence_date'), name='unique_template_occurrence'),
        ),
        migrations.AddIndex(
            model_name='blocktemplate',
            index=models.Index(fields=['user', 'active'], name='focus_block_user_id_47df8c_idx'),
        ),
        migrations.AddConstraint(
            model_name='blocktemplate',
            constraint=models.CheckConstraint(condition=models.Q(('end__gt', models.F('start'))), name='template_positive_length'),
        ),
        migrations.AddConstraint(
            model_name='blocktemplate',
            constraint=models.CheckConstraint(condition=models.Q(('weekday__lte', 6)), name='template_weekday'),
        ),
        migrations.AddConstraint(
            model_name='blocktemplate',
            constraint=models.CheckConstraint(condition=models.Q(('interval_weeks__gte', 1), ('interval_weeks__lte', 12)), name='template_interval'),
        ),
    ]
