# Generated by Django 5.2.18 on 2026-10-07 13:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("focus", "0003_blocktemplate_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="blocktemplate",
            name="frequency",
            field=models.CharField(
                choices=[("daily", "Daily"), ("weekly", "Weekly")], default="weekly", max_length=6
            ),
        ),
        migrations.AddConstraint(
            model_name="blocktemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(("frequency__in", ["daily", "weekly"])),
                name="template_frequency",
            ),
        ),
    ]
