# Generated by Django 5.2.18 on 2026-10-07 22:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0005_task_completed_on_task_focus_task_user_id_1fc084_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='day_rollover',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
