# Generated by Django 5.2.18 on 2026-10-07 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0006_preferences_day_rollover'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='automatic',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TaskFocusSpan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_spans', to='focus.session')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='focus.task')),
            ],
            options={
                'ordering': ['started_at', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('session',), name='one_open_task_span')],
            },
        ),
    ]
